# taken from here: https://kerkour.com/rust-github-actions-ci-cd
name: CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
